project:
  type: book
  output-dir: docs

engine: knitr

filters:
  - webr

book:
  chapters:
    - index.qmd
    - Week1.qmd
    - Week2.qmd
    - Week3.qmd
    - Week4.qmd
    - Week5.qmd
    - Week6.qmd
    - Week7.qmd
    - Week8.qmd
    - Week9.qmd
    - references.qmd

bibliography: references.bib
citeproc: true
link-citations: true

format:
  html:
    theme: cosmo
    reference-location: document
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
