project:
  type: book
  output-dir: docs

engine: knitr

filters:
  - webr

book:
    chapters:
        - href: index.qmd
          text: "Introduction"
        - Week1.qmd
        - Week2.qmd
        - Week3.qmd
        - Week4.qmd
        - Week5.qmd
        - Week6.qmd
        - Week7.qmd
        - Week8.qmd
        - Week9.qmd
        - references.qmd
bibliography: references.bib

execute:
  freeze: false
  cache: false

format:
  html:
    theme: cosmo
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
    knitr:
      opts_chunk:
        dev: "pdf"
