# Introduction {.unnumbered}

## Background

I am currently enrolled in STATS200Q: Philosophical Foundations of Statistics with Professor Dennis Sun (technically just finished). It is a small class, with about twelve people, allowing Professor Sun to dive into the material while maintaining a level of connection with the students. I have greatly appreciated this element as it has allowed me to ask many questions along the way!

In my statistical journey, this class served as a follow-up to STATS118, which I took in the Fall with Professor Gene Kim. Put simply, that class was very difficult. It involved a lot of mathematical computation and required students to pick up patterns and manipulate expressions into known distributions.

As mentioned in the title, STATS200Q feels much more philosophical. It is still no doubt a math class, but it opts for less computation than 118 and more answering of "Why?". Looking back, many of the strategies I learned in 118 were "frequentist". However, even after taking that final exam, I would not have been able to explain what that term meant.

In STATS200Q, we have learned about the differences between frequentist and Bayesian statistics and how they approach problems separately. Each week throughout the quarter, we had a small homework assignment. This final book is an extension of that. Each assignment is its own chapter, and I have additionally added a "Background" section to each chapter. Put together, this should make it feel like a tightly-knit narrative.

This introduction chapter is no different. Sadly, this is the end of the "Background" section. Below I will explain the distribution and dataset I focused my studies on. I hope you enjoy!

NOTE: There are chapters in the book with multiple R blocks. Some R blocks call on variables that were defined in a separate R block earlier in that chapter. So, please make sure to run the R code in order for each chapter.

## My Dataset and Distribution

We were each assigned a distribution to focus our analysis on. I chose the Negative Binomial distribution, and the variant that measures how many failures before a successful attempt. I focus my data analysis on a specific COVID hospital dataset, which keeps track of who infected who in that hospital. In my dataset, the data with the negative binomial distribution is the number of people each person infected beyond the first person (This is because all infectors in the dataset infected at least one person, so we subtract one to have a healthy amount of zero values).

Source: The original dataset is from this GitHub link: <https://github.com/linwangidd/covid19_transmissionPairs_China/blob/master/transmission_pairs_covid_v2.csv>.

The PMF for the variant of the Negative Binomial I will be analyzing is:

$$
\begin{aligned}
    P(X=x) &= \binom{x + r- 1}{x} p^r (1 - p)^x \\
\end{aligned}
$$

If you want to do any analysis of the data, feel free to code in the block below.

`dat` is the dataset.

`x` is the number of people each person infected beyond the first person, and follows a negative binomial distribution.

```{webr-r}
dat <- read.csv("https://raw.githubusercontent.com/Ryder4real/STATS200Q_Book/main/transmission_pairs_covid_v2.csv")
x <- as.vector(table(dat$infector_id)) - 1
length(x)

```

As seen in the code block above, there are 807 patients in my dataset.

Traditionally, in this version of the Negative Binomial distribution, $p$ is meant to be the probability of success for each trial and $r$ is meant to be the fixed number of successes we are waiting for (which hypothetically would be $1$ in this case). However, in the real world, studies have found that negative binomials can effectively model hospital datasets where the parameters have slightly altered meanings (I will mention one such study at the end of this chapter).

In my dataset, $p$ is the probability of a transmission opportunity not resulting in an infection (perhaps counter-intuitively, the lower the $p$, the more infectious). $r$ is the dispersion parameter, meaning it is a measure of how heavily clustered the transmissions are.

$r$ seems to fit best below $1$, meaning there are many individuals who do not pass the virus to anyone beyond the first person. This makes sense as, from the code below, we can see that $507$ of the individuals in the dataset have a value of $0$, meaning they did not pass the virus to anyone beyond the first person.

```{webr-r}
sum(x == 0)
```

It is important to note that the PMF I wrote out earlier includes $r$ in a choose function. Technically, this is not allowed, as $r$ is not necessarily an integer for my dataset. However, in practice, we can just use the gamma fraction to replace the choose function whenever computations are needed.

For some quick context, there is a great 2005 paper by @lloydsmith2005 titled "Superspreading and the effect of individual variation on disease emergence", which found the negative binomial distribution to be a great fit for a 2002-2004 SARS epidemic in Singapore and Beijing, and their $\hat{r}$ was $0.16$.

As a quick note, for this class, we mainly focused on analyzing one parameter. So, for many of these chapters, I will fix $r$, and analyze $p$.
