---
title: "Generalized Likelihood Ratio Test"
---

## Background

Last chapter, we talked about hypothesis testing and the Uniformly Most Powerful Test. Tests like these are possible when our $H_A$ is a greater than or less than, like $H_A: \theta < 1$. However, what if we had $H_A: \theta \neq 1$.

What maximizes power for $\theta = 0.5$ is different than what maximizes power for $\theta = 1.5$. So, we cannot have a Uniformly Most Powerful Test. Instead, we set up the Generalized Likelihood Ratio Test. The idea is still the same, where we still want to find the $x$ values that maximize $\frac{f_{\text{Alternative Hypothesis}}(x)}{f_{\text{Null Hypothesis}}(x)}$. The problem is that if $H_A: \theta \neq 1$, different values maximize $f_\text{Alternative Hypothesis}(x)$ depending on if $\theta$ is above or below $1$.

So, our solution is to find a $\theta$ that maximizes the numerator. This means that we can re-write the ratio we want to maximize as: $\frac{\max_\theta \mathcal{L}(\theta)}{\mathcal{L}(\theta_0)}$.

The $\theta$ that maximizes the likelihood is the MLE. This means that we want to maximize the ratio $\frac{f_{\hat{\theta}_{MLE}}(x)}{f_{\theta_0}(x)}$.

## Generalized Likelihood Ratio Test

So, let's apply this to my dataset. First, let's bring my hospital dataset into R.

```{webr-r}
dat <- read.csv("https://raw.githubusercontent.com/Ryder4real/STATS200Q_Book/main/transmission_pairs_covid_v2.csv")
x <- as.vector(table(dat$infector_id)) - 1
```

I mention this in Chapter 6, but as a reminder:

In my hospital dataset, the data that has a negative binomial distribution is the number of people each person infected beyond the first person (This is because all infectors in the dataset infected at least one person, so we subtract one to have a healthy amount of zero values). Google says that for the Flu, the average person with the disease spreads it to 1-2 people. As our negative binomial distribution only counts the number of additional people each person infects after the first, then setting $E[X] = 0.5$ feels fair. In other words, for the flu, it reasonable to stay the average person in a hospital with a disease infects 0.5 extra people. That would means that $\mathbb{E}[X] = \frac{r(1-p)}{p} = 0.5$.

I isolated for $p$ in Chapter 6, and got that $p = 0.6$:

Let's say our null hypothesis is $H_0$: $p = 0.6$. Now, we are curious if maybe COVID has a different degree of infectiousness than the flu (not considering other considerations like how my dataset is limited to people only already at the hospital). This would mean that $E[X] \neq 0.5$, and $p \neq 0.6$.

So, this gives us:

$H_0$: $p = 0.6$

$H_A$: $p \neq 0.6$

As we mentioned above, for this type of hypothesis test, we try to maximize the ratio:

$\frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)}$

We can write this out as:

$$
\begin{aligned}
\frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)} &= \frac{\prod _{i=1}^n \binom{x_i + r - 1}{x} p^r (1 - p)^{x_i}}{ \prod_{i=1}^n \binom{x_i + r - 1}{x_i} (p_0)^r (1 - p_0)^{x_i}} \\
\end{aligned}
$$

We know that for the numerator, the $p$ that gives the greatest likelihood is $\hat{p}_{MLE}$. In Chapter 1, I calculate the $\hat{p}_{MLE}$ for multiple samples of the Negative Binomial distribution is $\frac{r}{r + \bar{x}}$.

$$
\begin{aligned}
\frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)} &= \frac{\prod _{i=1}^n \binom{x_i + r - 1}{x} (\frac{r}{r + \bar{x}})^r (1 - \frac{r}{r + \bar{x}})^{x_i}}{ \prod_{i=1}^n \binom{x_i + r - 1}{x_i} (p_0)^r (1 - p_0)^{x_i}} \\
\end{aligned}
$$

We can simplify this to:

$$
\begin{aligned}
\frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)} &= \frac{\prod _{i=1}^n \binom{x_i + r - 1}{x} (\frac{r}{r + \bar{x}})^r (1 - \frac{r}{r + \bar{x}})^{x_i}}{ \prod_{i=1}^n \binom{x_i + r - 1}{x_i} (p_0)^r (1 - p_0)^{x_i}} \\
\frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)} &= \frac{(\frac{r}{r + \bar{x}})^{nr} (1 - \frac{r}{r + \bar{x}})^{\sum_{i=1}^n x_i}}{(p_0)^{nr} (1 - p_0)^{\sum_{i=1}^n x_i}} \\
\end{aligned}
$$

We want to reject when $\frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)} \geq c$, where: $$P(\texttt{test\_statistic} \geq c) = \alpha = 0.05$$

However, this does not simplify to a distribution I recognize, so I cannot solve for $c$.

Still, we want to maximize this function. As log is monotonic, we can take the logarithm of the fraction.

$$
\begin{aligned}
\log \Big(\frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)} \Big) &= \log \Bigg( \frac{(\frac{r}{r + \bar{x}})^{nr} (1 - \frac{r}{r + \bar{x}})^{\sum_{i=1}^n x_i}}{(p_0)^{nr} (1 - p_0)^{\sum_{i=1}^n x_i}} \Bigg)\\
\log \Big(\frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)} \Big) &= nr \log(\frac{r}{r + \bar{x}}) + \sum_{i=1}^n x_i \log(1 - \frac{r}{r + \bar{x}})- \Big( nr \log(p_0)  + \sum_{i=1}^n x_i \log(1 - p_0) \Big)\\
\log \Big(\frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)} \Big) &= nr \log \Big(\frac{\frac{r}{r + \bar{x}}}{p_0}\Big) + \sum_{i=1}^n x_i \log \Big( \frac{1-\frac{r}{r + \bar{x}}}{1-p_0} \Big) \\
\log \Big(\frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)} \Big) &= nr \log \Big(\frac{\frac{r}{r + \bar{x}}}{p_0}\Big) + \sum_{i=1}^n x_i \log \Big( \frac{1-\frac{r}{r + \bar{x}}}{1-p_0} \Big)
\end{aligned}
$$

Once again, this also does not simplify to a distribution I recognize. So, we are left to either simulate or take the asymptotic distribution.

### Simulation

Let's simulate many times under the null hypothesis, and calculate $\frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)}$ each time. For brevity, I will refer to $\frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)}$ as $\Lambda$. Then, as we want to keep $\alpha \leq 0.05$, we would reject if $\Lambda$ for our data is greater than the $95$th percentile of the simulated $\Lambda$s.

Remember: $\Lambda = \frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)} = \frac{(\frac{r}{r + \bar{x}})^{nr} (1 - \frac{r}{r + \bar{x}})^{\sum_{i=1}^n x_i}}{(p_0)^{nr} (1 - p_0)^{\sum_{i=1}^n x_i}}$.

However, to prevent underflow, I will take the logarithm.

$\log \Big(\frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)} \Big) = nr \log \Big(\frac{\frac{r}{r + \bar{x}}}{p_0}\Big) + \sum_{i=1}^n x_i \log \Big( \frac{1-\frac{r}{r + \bar{x}}}{1-p_0} \Big)$

```{webr-r}
n = length(x)
r = 0.75
p_0 = 0.6
n_sims = 10000

sims <- replicate(n_sims, {
    data <- rnbinom(n = n, size = r, prob = p_0)
    
    data_bar = mean(data)
    data_sum = sum(data)
    
    p_mle = r / (r + data_bar)
    
    first_term = n * r * log(p_mle / p_0)
    second_term = data_sum * log((1 - p_mle) / (1 - p_0))
    
    log_lambda = first_term + second_term
    log_lambda
}
)
quantile(sims, 0.95)
```

So, our test statistic is $\log \Big(\frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)} \Big)$ and our $c$ is about $1.933$, depending on the simulation. So, if $\Lambda$ for my data is above 1.933, we reject $H_0$.

So, let's calculate $\log (\Lambda)$, while setting $r=0.75$.

```{webr-r}
n = length(x)
r = 0.75
p_0 = 0.6

x_bar = mean(x)
x_sum = sum(x)
    
p_mle = r / (r + x_bar)
    
first_term = n * r * log(p_mle / p_0)
second_term = x_sum * log((1 - p_mle) / (1 - p_0))
    
log_lambda = first_term + second_term
log_lambda
```

As $\log (\Lambda)$ is 23.55, which is $>c$, we reject $H_0$.

A power curve stricly from simulation is generated in the code block below.

Note, for the sake of runtime, I lowered `n` to 50 in the code. I recommend messing around and changing `n` to see how the power curve changes.

```{webr-r}
# I encourage you to change n to see how this affects the power curve
n <- 50

p_0 <- 0.6
r = 0.75
n_sims <- 5000  

# Simulating under the null hypothesis to find the 95th quartile (our c value)
null_sims <- replicate(n_sims, {
  data <- rnbinom(n = n, size = r, prob = p_0)
  data_bar <- mean(data)
  
  p_mle <- r / (r + data_bar)
  
  # Avoid any potential log(0) errors
  if (p_mle == 1) { 
    p_mle <- 0.9999 
  }
  
  # Log-likelihood ratio logic
  log_lambda <- n * r * log(p_mle / p_0) + sum(data) * log((1 - p_mle) / (1 - p_0))
  log_lambda
})
raw_crit_val <- quantile(null_sims, 0.95)

# Set up parameters for power curve
p_alt_space <- seq(0.01, 1, by = 0.05)
powers <- c()  

# Simulate alternative hypothesis / null hypothesis and keep track for each one whether we should reject

for (p_alt in p_alt_space) {
  
  rejections <- replicate(n_sims, {

    data_alt <- rnbinom(n = n, size = r, prob = p_alt)
    data_bar_alt <- mean(data_alt)
    
    p_mle_alt <- r / (r + data_bar_alt)
    
    # Avoid any potential log(0) errors
    if (p_mle_alt == 1) { 
      p_mle_alt <- 0.9999 
    }
    
    # Calculate log_lambda
    log_lambda_alt <- n * r * log(p_mle_alt / p_0) + sum(data_alt) * log((1 - p_mle_alt) / (1 - p_0))
    
    # Check if we should reject?
    log_lambda_alt > raw_crit_val
  })
  
  # Append the mean rejection rate (power) for this specific p_alt
  powers <- c(powers, mean(rejections))
}

# Plot results
plot(p_alt_space, powers, type = "l", lwd = 3, col = "#2c3e50",
     xlab = expression(p), ylab = "Power", 
     main = "Empirical GLRT Power Curve", ylim = c(0, 1))

abline(v = p_0, col = "#e74c3c", lty = 2)  
abline(h = 0.05, col = "gray50", lty = 3) 
```

I recommend going back in the code and seeing how changing `n` can effect your power curve.

### Asymptotic

We learned in class that under Wilks' Theorem, when only solving for only one parameter and setting all the potential parameters as fixed, then for large $n$:

$2 \log(\frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)}) \sim \chi^2_1$.

Remember, we want to reject when $2 \log(\frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)})$ is large.

So, we set up our rejection bound as:

$2 \log(\frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)}) \geq c$, where $c$ the $95\%$ percentile of the chi-squared distribution.

So, let's figure out our $c$:

We can run this in code:

```{webr-r}
alpha = 0.05
p = 0.6
c = qchisq(1-alpha, 1)
c
```

So, from the code block above, $c = 3.841459$

Now, let's check our data. Let's assume $r = 0.75$. Remember that Wilks' Theorem states that for large $n$ when there is only one unknown parameter.

$2 \log(\frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)}) \sim \chi^2_1$.

For our Negative Binomial: $\log \Big(\frac{\max_{p} \mathcal{L}(p)}{\mathcal{L}(p_0)} \Big) = nr \log \Big(\frac{\frac{r}{r + \bar{x}}}{p_0}\Big) + \sum_{i=1}^n x_i \log \Big( \frac{1-\frac{r}{r + \bar{x}}}{1-p_0} \Big)$

Let's proceed with $r=0.75$.

```{webr-r}
n = length(x)
r = 0.75
x_sum = sum(x)
x_bar = mean(x)
p_0 = 0.6
p_mle = r / (r + x_bar)
log_part = n * r * log(p_mle / p_0) + x_sum * log((1 - p_mle) / (1 - p_0))
test_stat = 2 * log_part
test_stat
```

So, we can see from the code block that our dataset's test statistic was 47.09489. If I just plug in the PMFs, I get the same value:

```{webr-r}
log_L_mle  <- dnbinom(x_sum, size = n * r, prob = p_mle, log = TRUE)
log_L_null <- dnbinom(x_sum, size = n * r, prob = p_0, log = TRUE)

test_stat_2 = 2 * (log_L_mle - log_L_null)
test_stat_2
```

As $47.1 > c$ (which was $3.841459$), for my COVID hospital dataset, we reject $H_0$.

This implies that we reject the hypothesis that COVID has the same contagious level as the flu (though this dataset is not perfect as it only consists of people already in the hospital who infected at least $1$ person, so I do not want to extrapolate too much). Another way to say this is that we accept the hypothesis that COVID does not have the same contagious level as the flu.

A power curve using Wilks' Theorem would be:

```{webr-r}
# Feel free to change this parameter (n) to see how it affects the curve
n = length(x)

p_alt <- seq(0, 1, by = 0.001)
alpha <- 0.05
crit_val <- qchisq(alpha, df = 1, lower.tail = FALSE)

lambda <- 2 * n * r * (log(p_alt / p_0) + ((1 - p_alt) / p_alt) * log((1 - p_alt) / (1 - p_0)))

lambda[p_alt == p_0] <- 0

power_curve <- pchisq(crit_val, df = 1, ncp = lambda, lower.tail = FALSE)

plot(p_alt, power_curve, type = "l", col = "#2c3e50", lwd = 3,
     xlab = expression(textstyle("p")),
     ylab = "Power",
     main = "GLR Power Curve (Wilks' Theorem)",
     ylim = c(0, 1), panel.first = grid(lty = "dotted", col = "gray70"))

abline(v = p_0, col = "#e74c3c", lty = 2, lwd = 2)   # Null Hypothesis baseline

legend("bottomright", 
       legend = c("Power Curve", "Null Hypothesis (p = 0.6)"),
       col = c("#2c3e50", "#e74c3c", "#27ae60"), 
       cex=0.6,
       lty = c(1, 2, 3), lwd = c(3, 2, 2), bg = "white")
```

Again, I recommend going back in the code and seeing how changing `n` can effect your power curve.
