---
title: "Sufficiency"
---

## Background

We have finally finished covering both frequentist and Bayesian hypothesis testing. This means we moved onto the final topic of this book: sufficiency.

A sufficient statistic $T(x_1,...,x_n)$, means that $T$ contains all useful information with respect to the data. This means that once we have $T$, we do not care how we got there. As a quick example, let's say that $T = \sum_{i=1}^n x_i$ and it is a sufficient statistic for $\theta$. This means that for properly estimating $\theta$, we do not need to know $x_1,...,x_n$. In fact, we only need to know $T$.

Furthermore, the Rao-Blackwell theorem says that for any unbiased estimator $\hat{\theta}$, then $\hat{\theta}_{RB} = \mathbb{E}[\hat{\theta}(T)]$ is also unbiased and $\text{Var}(\hat{\theta}_{RB}) \leq \text{Var}(\hat{\theta})$. So, this means that the best unbiased estimator only references the data with respect to the sufficient statistic $T$.

A quick proof is below. First, let's show that if $\hat{\theta}$ is unbiased, then so is $\hat{\theta}_{RB}$.

$$
\begin{aligned}
  \mathbb{E}[\hat{\theta}_{RB}] &= \mathbb{E}[\mathbb{E}[\hat{\theta} | T]]  \\
  \mathbb{E}[\hat{\theta}_{RB}] &= \mathbb{E}[\hat{\theta}] \text{   [NOTE: From the Law of Total Expectation]}
\end{aligned}
$$

So, this means that the expected value of both estimators is the same, so they have the same bias. Next, let's show the variance part.

$$
\begin{aligned}
\text{Var}(\hat{\theta}) &= \mathbb{E}[(\text{Var}(\hat{\theta}|T)] + \text{Var}(\mathbb{E}[\hat{\theta}|T]) \text{   [NOTE: From the Law of Total Variance]} \\
\text{Var}(\hat{\theta}) &= (\text{value} \geq 0) + \text{Var}(\hat{\theta}_{RB})
\end{aligned}
$$

So, we can see $\text{Var}(\hat{\theta}_{RB}) \leq \text{Var}(\hat{\theta})$.

This gives way to the sufficiency principle: "If you have a sufficient statistic, use it."

The MLE and Posterior Mean are always both functions of a sufficient statistic. In general, our estimators are usually already functions of sufficient statistics, meaning we do not usually have to apply the Rao-Blackwell theorem to improve our estimator (this process is called Rao-Blackwellization).

## Sufficient Statistic

In class, we learned that for data $X_i,...X_n$ and parameter $\theta$, a statistic $T(x_i,...x_n)$ is sufficient if either of the following hold:

1: $f_\theta(x_i,...x_n) = g\Big( \theta, T(x_1,...,x_n)\Big) \cdot h(x_1,...,x_n)$,

$\quad$ where:

$\qquad g\Big( \theta, T(x_1,...,x_n)\Big)$ depends on $\theta$ only through $T$

$\qquad h(x_1,,...x_n)$ depends only on $(x_1,,...x_n)$ and not on $\theta$

2.  $P(X_i=x_1,...,X_n=x_n | T = t)$ does not depend on $\theta$.

For my Negative Binomial dataset, $p$ is the parameter we are interested in estimating, so $p$ will be our $\theta$.

I will show that for my distribution, both definitions hold:

### First Proof

The PMF of my negative Binomial Distribution: $X_1,...,X_n \sim \text{NegBin}(r, p)$ is:

$$
\begin{aligned}
    f_p(x_1,...,x_n) &= \prod_{i=1}^n \binom{x_i + r- 1}{x_i} p^r (1 - p)^{x_i}
\end{aligned}
$$

We can simplify this into:

$$
\begin{aligned}
    f_p(x_1,...,x_n) &= \prod_{i=1}^n \binom{x_i + r- 1}{x_i} p^r (1 - p)^{x_i} \\
     &= p^{rn} \prod_{i=1}^n \binom{x_i + r- 1}{x_i} (1 - p)^{x_i} \\
    &= p^{rn} \Bigg( \prod_{i=1}^n \binom{x_i + r- 1}{x_i} \Bigg) (1 - p)^{\sum_{i=1}^nx_i} 
\end{aligned}
$$

We can re-write this as:

$$
\begin{aligned}
 f_p(x_1,...,x_n) &= p^{rn}(1 - p)^{\sum_{i=1}^n x_i} \cdot  \prod_{i=1}^n \binom{x_i + r- 1}{x_i} 
\end{aligned}
$$

Now, as we have been doing, let's assume $r$ is fixed and $p$ is the parameter we are interested in estimating.

Here, if we set $T(X_1,...x_n) = \sum_{i=1}^n x_i$, then we can rewrite the equation as:

$$
\begin{aligned}
 f_p(x_1,...,x_n) &= p^{rn}(1 - p)^{\sum_{i=1}^n x_i} \cdot  \prod_{i=1}^n \binom{x_i + r- 1}{x_i} \\
&= p^{rn}(1 - p)^{T} \cdot  \prod_{i=1}^n \binom{x_i + r- 1}{x_i} \\
&= g\Big( p, T(x_1,...,x_n)\Big)  \cdot  h(x_1,,...x_n)
\end{aligned}
$$

where:

1.  $g\Big( p, T(x_1,...,x_n)\Big) = p^{rn}(1 - p)^{T}$

2.  $h(x_1,,...x_n) = \prod_{i=1}^n \binom{x_i + r- 1}{x_i}$

As we were able to write our PDF in terms of $g\Big(p, T(x_1,...,x_n)\Big)  \cdot  h(x_1,,...x_n)$, then this means $T(x_1,...,x_n)$ is a sufficient statistic.

So, for the Negative Binomial distribution, $\sum_{i=1}^n x_i$ is a sufficient statistic.

### Second Proof

Similarly, we could have also confirmed this using the other definition we learned in class, that $P(X_1=x_1,...,X_n=x_n | T = t)$ does not depend on $p$.

$$
\begin{aligned}
P(X_1=x_1,...,Xn=x_n | T=t) = \frac{P(X_1=x_1,...,X_n=x_n, T=t)}{P(T=t)} 
\end{aligned}
$$

$T$ is the sum of i.i.d. $\text{NegBin}(r, p)$ random variables. So, $T$ is a $\text{NegBin}(nr, p)$ random variable.

So, we get:

$$
\begin{aligned}
P(X_1=x_1,...,Xn=x_n | T=t) &= \frac{P(X_1=x_1,...,X_n=x_n, T=t)}{P(T=t)} \\
P(X_1=x_1,...,Xn=x_n | T=t) &= \frac{p^{rn}(1 - p)^{t} \cdot  \prod_{i=1}^n \binom{x_i + r - 1}{x_i}}{\binom{t + nr- 1}{t} p^{rn} (1 - p)^{t}} \\
P(X_1=x_1,...,Xn=x_n | T=t) &= \frac{  \prod_{i=1}^n \binom{x_i + r - 1}{x_i}}{\binom{t + nr - 1}{t} } \\
\end{aligned}
$$

As we can see, this does not depend on $p$, proving once again that $T(x_1,...x_n) = \sum_{i=1}^n x_i$ is a sufficient statistic.

## Seeing This in My MLE and Posterior Mean

As I mentioned earlier, the MLE and Posterior Mean are both always functions of a Sufficient Statistic. From Chapter 1, we have that:

$$
\begin{aligned}
\hat{p}_{MLE} &= \frac{r}{r + \bar{x}} \\
\hat{p}_{PM} &= \frac{1 + nr}{2 + nr + \sum_{i=1}^n x_i}
\end{aligned}
$$

As $T(x_1,...x_n) = \sum_{i=1}^n x_i$, we can rewrite our MLE and Posterior Mean as functions of T:

$$
\begin{aligned}
\hat{p}_{MLE} &= \frac{r}{r + \frac{T}{n}} \\
\hat{p}_{posterior} &= \frac{1 + nr}{2 + nr + T}
\end{aligned}
$$
