---
title: "Further Evaluating Estimators"
---

## Background

This chapter covers a variety of topics. First, I will dive into some cool properties regarding the score, which is the derivative of the log likelihood. One integration technique I will use for this is "Differentiation Under the Integral Sign". It is a cool trick that allows you to move a derivative outside of the integral.

Then, we will take a nice short break from proofs, and I will mention another way to evaluate estimators. In Chapter 1, we looked at the bias and variance of $\hat{p}_{MLE}$ and $\hat{p}_{PM}$, but this time I will use frequentist Mean Squared Error to compare them. This is defined as MSE = $\mathbb{E}[(\hat{\theta} - \theta)^2]$. The MSE can famously be decomposed as the (Bias$^2$ + Variance). So, while last chapter we looked at bias and variance, MSE serves as an all-encompassing metric. So, I will compare the MSE of my MLE and Posterior Mean from Chapter 1.

Alas, after discussing MSE, our short break from proofs will have concluded. I will next prove the Cramer-Rao Lower Bound (CRLB), evaluate the CRLB for my distribution, and see if it is relevant to the MLE and Posterior Mean I calculated in Chapter 1. In class, we learned that the CRLB is a lower bound to the variance of an unbiased estimator. This means that of all unbiased estimators, if one reaches the CRLB, then it is the best unbiased estimator, as it would have the lowest MSE. This is very insightful. It means once we've reached that bound, there is no point evaluating other unbiased estimators, as there cannot be an unbiased estimator with a lower variance and MSE than the one that reaches the CRLB.

As an extra note, the CRLB is defined as $\frac{1}{I(\theta)}$, where $I(\theta)$ is defined as the variance of the score (which is the derivative of the log-likelihood). I will prove this later on in this chapter. It is important to note that some of the equations I derive in the first part of this chapter will make it easier to solve for the CRLB for my distribution.

## Proving $\text{Var}(\ell'(\theta)) = -\mathbb{E}[\ell''(\theta)]$

For any PMF/PDF $f_\theta(x)$, the log-likelihood of $x$ can be written as $\ell_x(\theta)$.

Another name for the derivative of the log-likelihood is the score. The expected value of the score is defined as $\mathbb{E}[\ell'_\theta(x)]$.

$$
\mathbb{E}[\ell'_x(\theta)] = \int_{-\infty}^\infty \ell'_x(\theta)f_\theta(x) dx
$$

Now, let's solve for $\ell'_x(\theta)$:

$$
\begin{aligned}
L_x(\theta) &= f_\theta(x) \\ 
\ell_x(\theta) &= \log(f_\theta(x)) \\
\frac{d}{d \theta} \ell_x(\theta) &= \frac{\frac{d}{d \theta} f_\theta(x)}{f_\theta(x)} \\
\ell'_x(\theta) &= \frac{\frac{d}{d \theta} f_\theta(x)}{f_\theta(x)}
\end{aligned}
$$

Substituting this into our expectation:

$$
\begin{aligned}
\mathbb{E}[\ell'_x(\theta)] &= \int_{-\infty}^\infty \frac{\frac{d}{d \theta} f_\theta(x)}{f_\theta(x)} f_\theta(x) dx \\
&= \int_{-\infty}^\infty \frac{d}{d \theta} f_\theta(x) dx \\
&= \frac{d}{d \theta} \int_{-\infty}^\infty f_\theta(x) dx \\
&= \frac{d}{d \theta} (1) = 0
\end{aligned}
$$ The fact that $\mathbb{E}[\ell'_x(\theta)] = 0$ is an important result and I use it again later on in this chapter.

Now, let's solve for $\text{Var}(\ell'(\theta))$.

We know: $\text{Var}(\ell'(\theta)) = \mathbb{E}[(\ell'(\theta))^2] - (\mathbb{E}[\ell'(\theta)])^2$.

Since $\mathbb{E}[\ell'_x(\theta)] = 0$:

$$
\text{Var}(\ell'(\theta)) = \mathbb{E}[(\ell'(\theta))^2] = \int_{-\infty}^\infty (\ell'_x(\theta))^2 f_\theta(x) dx
$$

Next, we relate $(\ell'_x(\theta))^2$ to the second derivative:

$$
\begin{aligned}
\ell''_x(\theta) = \frac{d}{d \theta} \left[ \frac{\frac{d}{d \theta} f_\theta(x)}{f_\theta(x)} \right] &= \frac{f_\theta(x) \frac{d^2}{d \theta^2} f_\theta(x) - (\frac{d}{d \theta} f_\theta(x))^2}{(f_\theta(x))^2} \\
\ell''_x(\theta) &= \frac{\frac{d^2}{d \theta^2} f_\theta(x)}{f_\theta(x)} - \left( \frac{\frac{d}{d \theta} f_\theta(x)}{f_\theta(x)} \right)^2 \\
\ell''_x(\theta)&= \frac{\frac{d^2}{d \theta^2} f_\theta(x)}{f_\theta(x)} - (\ell'_x(\theta))^2
\end{aligned}
$$

Rearranging gives $(\ell'_x(\theta))^2 = \frac{\frac{d^2}{d \theta^2} f_\theta(x)}{f_\theta(x)} - \ell''_x(\theta)$.

Subbing this into $\text{Var}(\ell'(\theta)) = \mathbb{E}[(\ell'(\theta))^2] = \int_{-\infty}^\infty (\ell'_x(\theta))^2 f_\theta(x) dx$ gives us:

$$
\begin{aligned}
\text{Var}(\ell'(\theta)) &= \int_{-\infty}^\infty f_\theta(x) \left( \frac{\frac{d^2}{d \theta^2} f_\theta(x)}{f_\theta(x)} - \ell''_x(\theta) \right) dx \\
&= \int_{-\infty}^\infty \frac{d^2}{d \theta^2} f_\theta(x) -  \ell''_x(\theta) f_\theta(x) dx \\
&= \int_{-\infty}^\infty \frac{d^2}{d \theta^2} f_\theta(x)  dx - \int_{-\infty}^\infty \ell''_x(\theta) f_\theta(x) dx \\
&= \frac{d^2}{d\theta^2} \int_{-\infty}^\infty f_\theta(x) dx- \mathbb{E}[\ell''_x(\theta)] \\
&= \frac{d^2}{d\theta^2} (1) - \mathbb{E}[\ell''_x(\theta)] \\
&= - \mathbb{E}[\ell''_x(\theta)]
\end{aligned}
$$

So, we have just shown that $\text{Var}(\ell'_x(\theta)) = -\mathbb{E}[\ell''_x(\theta)]$. This value is also known as the Fisher Information, or $I(\theta)$.

## MSE

In Chapter 1, I derived that if $X_1,...,X_n \sim \text{NegBin}(r, p)$, then: $\hat{p}_{MLE} = \frac{r}{r + \bar{x}}$ and $\hat{p}_{PM}$ = $\frac{1 + nr}{2 + nr + \sum x_i}$.

We previously analyzed the bias and variance of these estimators. Now, let's analyze their MSE, which is $\mathbb{E}[(\hat{p} - p)^2]$. As mentioned in the Background section, this can be rewritten as Bias$^2$ + Variance.

Below is a simulation that prints out Mean Squared Error for different $p$, for when $n=50$ and $r=0.5$.

```{webr-r}
n <- 50 
true_size <- 0.5 #r

p_grid <- seq(0.01, 0.99, length.out = 40)
mse_results <- sapply(p_grid, function(p) {
  
  # Run simulations for each specific p in the grid
  temp_sims <- replicate(10000, {
    x <- rnbinom(n = n, size = true_size, prob = p)
    x_avg = mean(x)
    x_sum = sum(x)
    
    p.mle <- true_size / (true_size + x_avg)
    p.pm <- (1 + n * true_size) / (2 + n * true_size + x_sum)
    
    c(mle = p.mle, pm = p.pm)
  })
  
  # Calculate MSE for this specific p
  mse_mle_p <- mean((temp_sims["mle",] - p)^2)
  mse_pm_p <- mean((temp_sims["pm",] - p)^2)
  
  c(mse_mle = mse_mle_p, mse_pm = mse_pm_p)
})

# Plotting the curve
plot(p_grid, mse_results["mse_mle",], type = "l", col = "blue", lwd = 2,
     main = "MSE for Different Estimators", 
     xlab = "True p", 
     ylab = "MSE",
     cex.main = 0.9,  
     cex.lab = 0.8,   
     cex.axis = 0.7)

lines(p_grid, mse_results["mse_pm",], col = "red", lwd = 2, lty = 2)
legend("topright", 
       legend = c("MLE", "Posterior Mean"), 
       col = c("blue", "red"), 
       lty = 1:2,
       cex = 0.6)
```

As we can see, at different true $p$ values, one estimator may be better than the other. This is an interesting result and means that we cannot declare one estimator to be universally better than the other using frequentist MSE.

## Proving the Cramer-Rao Lower Bound

As mentioned in the "Background" section, the CRLB is a lower bound to the variance of an unbiased estimator. Let's show why this is the case.

First, let $t(x)$ be any unbiased estimator of $\theta$. Now let's solve for $\text{Cov}(t(x), \ell'_x(\theta))$.

$$
\begin{aligned}
\text{Cov}(t(x), \ell'_x(\theta)) &= \mathbb{E}[t(x) \cdot \ell'_x(\theta)] - \mathbb{E}[t(x)] \mathbb{E}[\ell'_x(\theta)] \\
\end{aligned}
$$ Now, in the first section of this Chapter, we showed that $\mathbb{E}[\ell'_x(\theta)] = 0$. So, let's apply that and continue to manipulate.

$$
\begin{aligned}
\text{Cov}(t(x), \ell'_x(\theta)) &= \mathbb{E}[t(x) \cdot \ell'_x(\theta)] - 0 \\
&= \int_{-\infty}^\infty t(x) \ell'_x(\theta) f_\theta(x) dx
\end{aligned}
$$

Now, in the first section we also showed that: $\ell'_x(\theta) = \frac{\frac{d}{d \theta} f_\theta(x)}{f_\theta(x)}$

Using this, we can say that:

$$
\begin{aligned}
\text{Cov}(t(x), \ell'_x(\theta)) &= \int_{-\infty}^\infty t(x) \frac{\frac{d}{d \theta} f_\theta(x)}{f_\theta(x)} f_\theta(x) dx \\
&= \int_{-\infty}^\infty t(x) \frac{d}{d \theta} f_\theta(x) dx \\
&= \frac{d}{d \theta}\int_{-\infty}^\infty t(x)  f_\theta(x) dx \\
&= \frac{d}{d \theta}\mathbb{E}[t(x)] \\
&= \frac{d}{d \theta} \theta \text{ [NOTE: This is because t(x) is unbiased]} \\
&= 1
\end{aligned}
$$ So, using the Cauchy-Schwarz Inequality, we can say that

$1 = \text{Cov}^2(t(x), \ell'_x(\theta)) \leq \text{Var}(t(x)) \text{Var}(\ell'_x(\theta))$

So, this means that:

$\frac{1}{\text{Var}(\ell'_x(\theta))} \leq \text{Var}(t(x))$.

So, this means that the variance of any unbiased estimator $t(x)$ must be greater than or equal to $\frac{1}{\text{Var}(\ell'_x(\theta))}$. And, if you remember earlier, this can be written as:

CRLB: $\frac{1}{\text{Var}(\ell'_x(\theta))} = \frac{1}{I(\theta)} = \frac{1}{-\mathbb{E}[\ell''_x(\theta)]}$

## Finding the CRLB

As described above, the CRLB for unbiased estimators is $\frac{1}{I(\theta)}$, where $I(\theta)$ is defined as the variance of the score. However, we proved above that the variance of the score, $\text{Var}(\ell'(\theta))$ is actually equivalent to $-\mathbb{E}[\ell''(\theta)]$

So, this means that the CRLB for unbiased estimators is $\frac{1}{-\mathbb{E}[\ell''_x(\theta)]}$.

In Chapter 1, I wrote for $X_1,...,X_n \sim \text{NegBin}(r, p)$, then $\ell'(p) = \frac{rn}{p} - \frac{\sum_{i=1}^n x_i}{1-p}$:

This means that $\ell''(p) = -\frac{rn}{p^2} - \frac{\sum_{i=1}^n x_i}{(1-p)^2}$

$$
\begin{aligned}
\mathbb{E}\left[\ell''(p)\right] &= -\left(\frac{rn}{p^2} + \frac{\mathbb{E}[\sum_{i=1}^n x_i]}{(1-p)^2} \right) \\
&= -\left(\frac{rn}{p^2} + \frac{rn(1-p)}{p(1-p)^2} \right) \\
&= -\frac{rn}{p^2(1-p)}
\end{aligned}
$$ So, the lowest possible variance for an unbiased estimator for $p$ is $\frac{p^2(1-p)}{rn}$.

## Does CRLB Apply?

In Week 1, we established from simulation that $\hat{p}_{MLE}$ is positively biased. Additionally, in class we learned that the $\hat{p}_{PM}$ is always biased toward the prior. Since the MLE and Posterior Mean are both biased in this case, the CRLB does not provide a strict lower bound for their variance.
