---
title: "MLE & Posterior Mean"
---

## Background

This chapter covers the Bayesian v Frequentist methods for estimating parameters. Imagine you flip a potentially weighted coin N times, and X are heads. How would you about estimating the true probability that the coin lands on heads? This is an interesting question, and Bayesians and frequentists would take different approaches.

This serves as a motivation for estimating parameters. Below, I will estimate $p$ in the Negative Binomial Distribution.

First, I will first use the Maximum Likelihood Estimation method to estimate $p$, which is the frequentist approach. Then, I will use a posterior mean, which is the Bayesian approach. Finally, I will compare them using my dataset.

## Maximum Likelihood Estimation

The frequentist method for estimating parameter is finding the MLE. Below I derive the MLE for $p$ in the negative binomial.

$X_1,...,X_n \sim \text{NegBin}(r, p)$

$$
\begin{aligned}
    P(X=x) &= \binom{x + r- 1}{x} p^r (1 - p)^x \\
    L_{x_1,...,x_n}(p) &= \prod_{i=1}^n \binom{x_i + r- 1}{x_i} p^r (1 - p)^{x_i} \\
    L_{x_1,...,x_n}(p) &= p^{rn} \prod_{i=1}^n \binom{x_i + r- 1}{x_i}  (1 - p)^{x_i} \\
    L_{x_1,...,x_n}(p) &= p^{rn} \Bigg(\prod_{i=1}^n \binom{x_i + r- 1}{x_i} \Bigg) (1 - p)^{\sum_{i=1}^n x_i} \\
    l_{x_1,...,x_n}(p) &= rn \log(p) + \sum_{i=1}^n \log \left(\frac{(x_i + r - 1)!}{{x_i}!(r - 1)!}\right) + \left(\sum_{i=1}^n x_i\right) \log(1 - p) \\
    \frac{d}{dp} l_{x_1,...,x_n}(p) &= \frac{d}{dp} \left( rn\log(p) + \sum_{i=1}^n \log \left(\frac{(x_i + r - 1)!}{{x_i}!(r - 1)!}\right) + \left(\sum_{i=1}^n x_i\right) \log(1 - p) \right) \\
    \frac{d}{dp} l_{x_1,...,x_n}(p) &= \left(\frac{rn}{p} - \frac{\sum_{i=1}^n x_i}{1 - p} \right) \\
    0 &= \frac{rn}{p} - \frac{\sum_{i=1}^n x_i}{1-p} \\
    \frac{rn}{p} &= \frac{\sum_{i=1}^n x_i}{1-p}  \\
    \frac{1-p}{p} &= \frac{\sum_{i=1}^n x_i}{rn} \\
    \frac{1}{p} - 1 &= \frac{\bar{x}}{r} \\
    \hat{p} &= \frac{r}{r + \bar{x}}
\end{aligned}
$$

## Posterior Mean

For the Bayesian method, we need a prior distribution that we will then have the data update. Let's use a Beta Prior with $\alpha=1, \beta = 1$ (which is actually just a uniform).

$$
\begin{aligned}
    f(p | x) &= \frac{f(p)f(x_1,...,x_n|p)}{f(x_1,...,x_n)}  \\
    f(p | x) &= \frac{\frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha)\Gamma(\beta)} p^{\alpha - 1} (1-p)^{\beta - 1} \prod_{i=1}^n \binom{x_i + r- 1}{x_i} p^r (1 - p)^{x_i}}{f(x_1,...,x_n)} \\ 
    f(p | x) &\propto p^{\alpha + nr - 1} (1-p)^{\beta + \sum x_i - 1}
\end{aligned}
$$

This results in $f(p | x) \sim \text{Beta}(\alpha + nr, \beta + \sum_{i=1}^n x_i)$.

$$
\begin{aligned}
    \mathbb{E}[P] &= \frac{\alpha + nr}{\alpha + \beta + nr + \sum_{i=1}^n x_i} \\
    \mathbb{E}[P] &= \frac{1 + nr}{2 + nr + \sum_{i=1}^n x_i}
\end{aligned}
$$

## My Dataset

Now, let's compute the two estimators on my dataset.

```{webr-r}
dat <- read.csv("https://raw.githubusercontent.com/Ryder4real/STATS200Q_Book/main/transmission_pairs_covid_v2.csv")
x <- as.vector(table(dat$infector_id)) - 1

x_bar  <- mean(x)
n      <- length(x)
x_sum  <- sum(x)

cat("x_bar:", x_bar, "\n")
cat("n:", n, "\n")
cat("x_sum:", x_sum, "\n")
```

As we can see from the code above, in my dataset, $\bar{x} = 0.7434944, n=807, \sum(x) = 600$.

So, plugging this in, we have:

$$
\begin{aligned}
    \hat{p}_{MLE} &= \frac{r}{r + 0.7434944} \\
    \hat{p}_{posterior} &= \frac{1 + 807r}{2 + 807r + 600}
\end{aligned}
$$

If we assume $r = 0.5$:

$$
\begin{aligned}
    \hat{p}_{MLE} &= \frac{0.5}{0.5 + 0.7434944 } = 0.402 \\
    \hat{p}_{posterior} &= \frac{1 + 807(0.5)}{2 + 807(0.5) + 600} = 0.401
\end{aligned}
$$

## Comparing Estimators

Now, let's compare the bias and variance of the two estimators. For the sake of evaluating our estimators, let's say true $p$ is $\frac{1}{3}$.

In my dataset, there are $807$ patients. After 10,000 simulations, the bias and variance of our estimators is:

```{webr-r}
n_obs <- 807
true_size <- 0.5 #r
true_p <- 1 / 3

sims <- replicate(10000, {
  x <- rnbinom(n = n_obs, size = true_size, prob = true_p)
  x_sum <- sum(x)
  x_avg = mean(x)
  p.mle <- true_size / (true_size + x_avg)
  
  p.pm <- (1 + n_obs * true_size) / (2 + n_obs * true_size + x_sum)
  
  c(mle = p.mle, pm = p.pm)
})

sims <- t(sims)

bias_mle <- mean(sims[,"mle"]) - true_p
bias_pm <- mean(sims[,"pm"]) - true_p

var_mle <- var(sims[,"mle"])
var_pm <- var(sims[,"pm"])

results <- data.frame(
  Metric = c("Bias", "Variance"),
  MLE = c(bias_mle, var_mle),
  Posterior_Mean = c(bias_pm, var_pm)
)

results
```

As we can see from the table produced by the code, $\hat{p}_{MLE}$ has positive bias while $\hat{p}_{PM}$ is biased toward the prior distribution (which in this case leads to positive bias).

$\hat{p}_{PM}$ has less slightly less variance. This is more apparent if you make `n_obs` smaller in the code.

Here is the the code for a histogram of $\hat{p}_{MLE}$ over many trials.

```{webr-r}
hist_mle <- hist(sims[, "mle"], 
     breaks = 30, 
     main = expression("Histogram of "* hat(p)[MLE]), 
     xlab = expression(hat(p)[MLE])
    )
```

Here is the the code for a histogram of $\hat{p}_{PM}$ over many trials.

```{webr-r}
hist_pm <- hist(sims[, "pm"], 
     breaks = 30, 
     main = expression("Histogram of "* hat(p)[PM]), 
     xlab = expression(hat(p)[PM])
     )
```
