---
title: "Asymptotic Distribution of the MLE"
---

## Background

This chapter will dive into the Asymptotic Distribution of the MLE we calculated in Chapter 1. This is interesting because calculating the bias and variance of the MLE by hand can be difficult. 

However, this can be made easier when dealing with large sample sizes by knowing that the distribution of the MLE approximates to a Normal as $n \rightarrow \infty$ It is kind of wild to think about no matter the original distribution, the distribution of the MLE always approaches the Normal distribution!

I will first simulate my distribution and look at a histogram of $\hat{p}_{MLE}$ as $n$ grows large. Then, I will prove that the MLE approximates to a Normal as $n \rightarrow \infty$ and apply that to my distribution.

## Simulating Distribution

Let's say $X_1, ...,X_n \sim \text{NegBin}(r, p)$, where $r=0.5$ and $p = \frac{1}{3}$.

We derived in Chapter 1. that $\hat{p}_{MLE} = \frac{r}{r + \bar{x}}$. Below is a histogram of $\hat{p}_{MLE}$ as $n$ grows large, in this case to $10,000$.

```{webr-r}
n_obs <- 10000  
true_size <- 0.5 #r
true_p <- 1 / 3

sims <- replicate(1000, {
  x <- rnbinom(n = n_obs, size = true_size, prob = true_p)
  x_sum <- sum(x)
  x_avg = mean(x)
  p.mle <- true_size / (true_size + x_avg)
  
  p.mle
})

sims <- t(sims)

hist_mle <- hist(sims, 
     breaks = 100, 
     main = expression("Histogram of "* hat(p)[MLE]), 
     xlab = expression(hat(p)[MLE])
)
```

As we can see, this looks pretty Normal, and it looks to be centered around $\frac{1}{3}$, which is what we set true $p$ to be.

## Proof of MLE Approaching a Normal Distribution

Now let's prove that the distribution of the MLE approaches a Normal distribution as $n$ gets large. This proof is a really cool one and involves many different concepts.

Let's start with the score of $\hat{\theta}_{MLE}$, which is $\ell'(\hat{\theta}_{MLE})$

Let's now Taylor expand $\ell'(\hat{\theta}_{MLE})$ around $\theta_0$.

$\ell'(\hat{\theta}_{MLE}) \approx \ell'(\theta_0) + \ell''(\theta_0)(\hat{\theta}_{MLE} - \theta_0)$

Now, remember that when solving for the MLE (as we did in Chapter 1), we set $\ell'(x) = 0$. This is because the MLE is defined as the $\theta$ value that maximizes the likelihood (and log-likelihood). 

So, as the MLE is a maximum of the log-likelihood function, this means that $\ell'(\hat{\theta}_{MLE}) = 0$.

So, plugging this in we get:

$0 = \ell'(\hat{\theta}_{MLE}) \approx \ell'(\theta_0) + \ell''(\theta_0)(\hat{\theta}_{MLE} - \theta_0)$

We can rearrange this to say:

$$
\begin{aligned}
  0 &\approx \ell'(\theta_0) + \ell''(\theta_0)(\hat{\theta}_{MLE} - \theta_0) \\
  - \ell'(\theta_0) &\approx \ell''(\theta_0)(\hat{\theta}_{MLE} - \theta_0) \\
  \hat{\theta}_{MLE} - \theta_0  &\approx \frac{-\ell'(\theta_0)}{\ell''(\theta_0)}
\end{aligned}
$$ 

Now, let's do some further manipulation.

$$
\begin{aligned}
  \hat{\theta}_{MLE} - \theta_0  &\approx \frac{-\ell'(\theta_0)}{\ell''(\theta_0)} \\
    \hat{\theta}_{MLE} - \theta_0  &= \frac{\frac{1}{n}\ell'(\theta_0)}{-\frac{1}{n}\ell''(\theta_0)} \\ 
      \hat{\theta}_{MLE} - \theta_0  &=  \frac{\frac{1}{n}\sum_{i=1}^n \ell'_{x_i}(\theta_0)}{-\frac{1}{n}\sum_{i=1}^n\ell''_{x_i}(\theta_0)} \\ 
      \sqrt{n}(\hat{\theta}_{MLE} - \theta_0)  &= \frac{\sqrt{n}(\frac{1}{n}\sum_{i=1}^n \ell'_{x_i}(\theta_0))}{-\frac{1}{n}\sum_{i=1}^n\ell''_{x_i}(\theta_0)} \\ 
\end{aligned}
$$

Now, let's say $Y = \ell'_{x_1}(\theta_0)$. This means that $\bar{Y} = \frac{1}{n} \sum_{i=1}^n \ell'_{x_i}(\theta_0)$.

This means that:

$$
\begin{aligned}
  \sqrt{n}(\hat{\theta}_{MLE} - \theta_0)  &= \frac{\sqrt{n} (\bar{Y} - 0)} {-\frac{1}{n}\sum_{i=1}^n\ell''_{x_i}(\theta_0)} \\ 
\end{aligned}
$$

Now, we can realize three things.

First, the CLT is defined as $\sqrt{n}(\bar{Y} - \mathbb{E}[Y_1]) \rightarrow N(0, Var(Y_1))$ \\
Second, as we showed in Chapter 2, $\mathbb{E}[Y_1] = \mathbb{E}[\ell'_{x_1}(\theta_0)] = 0$. \\
Third, also from Chapter 2, we showed that $I(\theta) = -\mathbb{E}[\ell''(\theta)] = \text{Var}(\ell'(\theta))$

So, this means that:

$$
\begin{aligned}
   \sqrt{n}(\hat{\theta}_{MLE} - \theta_0) \rightarrow \frac{N(0, \text{Var}(\ell'_{x_1}(\theta_0))}{\text{Var}(\ell'(\theta_0))} \\ 
    \sqrt{n}(\hat{\theta}_{MLE} - \theta_0) \rightarrow N \Big(0, \frac{1}{\text{Var}(\ell'_{x_1}(\theta_0))}\Big) \\ 
  \sqrt{n}(\hat{\theta}_{MLE} - \theta_0) \rightarrow N \Big(0, \frac{1}{I_{x_1}(\theta)}\Big) \\ 
\end{aligned}
$$

Isolating for $\hat{p}_{MLE}$, we have that $\hat{p}_{MLE} \rightarrow N\left(p, \frac{1}{nI_{x_1}(\theta)}\right)$

## Asymptotic Calculation

As shown above, using the CLT and Taylor approximation, we can see that as $n$ grows large, we have that $\hat{p}_{MLE} \rightarrow N\left(p, \frac{1}{nI_{x_1}(\theta))}right)$

So, let's solve for $I_{x_1}(\theta)$. Once again, from Chapter 2, we know that $I(\theta) = -\mathbb{E}[\ell''(\theta)] = \text{Var}(\ell'(\theta))$

Taking the score that we got from Chapter 1 (while solving for the MLE), we have:

$$
\frac{d}{dp} \ell_{x_1,...,x_n}(p) = \left(\frac{rn}{p} - \frac{\sum x}{1 - p} \right)
$$

As we only want to work with one observation now, we will set $n=1$.

$$
\ell ^\prime_{x_1} (p) = \left(\frac{r}{p} - \frac{x}{1 - p} \right)
$$

Let's solve for $-\mathbb{E}[\ell''(\theta)]$.

$$
\begin{aligned}
\ell ^\prime_{x_1} (p) &= \frac{r}{p} - \frac{x}{1 - p}  \\
\frac{d^2}{dp^2} \ell_{x_1} (p) &= \frac{-r}{p^2} - \frac{x}{(1 - p)^2} \\
-\mathbb{E}[\ell ^{\prime \prime}_{x_1} (p)] &= \frac{r}{p^2} + \frac{\mathbb{E}[x]}{(1 - p)^2} \\
-\mathbb{E}[\ell ^{\prime \prime}_{x_1} (p)] &= \frac{r}{p^2} + \frac{\Big(\frac{r(1-p)}{p}\Big)}{(1 - p)^2} \\
-\mathbb{E}[\ell ^{\prime \prime}_{x_1} (p)] &= \frac{r}{p^2} + \frac{r}{p(1 - p)} \\
-\mathbb{E}[\ell ^{\prime \prime}_{x_1} (p)] &= \frac{r(1-p)}{p^2(1-p)} + \frac{rp}{p^2(1 - p)} \\
-\mathbb{E}[\ell ^{\prime \prime}_{x_1} (p)] &= \frac{r(1-p) + rp}{p^2(1-p)}  \\
-\mathbb{E}[\ell ^{\prime \prime}_{x_1} (p)] &= \frac{r(1 - p + p)}{p^2(1-p)}  \\
-\mathbb{E}[\ell ^{\prime \prime}_{x_1} (p)] &= \frac{r}{p^2(1-p)}  \\
\end{aligned}
$$

So, we have

$$
  \sqrt{n} (\hat{p}_{MLE} - p) \rightarrow N\left(0, \frac{p^2(1-p)}{r}\right)
$$

And again isolating for $\hat{p}_{MLE}$, we have:

$$
\hat{p}_{MLE} \overset{\cdot}{\sim} N\left(p, \frac{p^2(1-p)}{nr} \right)
$$

## Graphing Asymptotic MLE Curve

Below is a curve with the distribution of $\hat{p}_{MLE}$ with $r=0.5$, $p= \frac{1}{3}$, and large $n (10,000)$, behind a red curve displaying the asymptotically normal distribution of $\hat{p}_{MLE}$.

```{webr-r}
hist_mle <- hist(sims, 
     breaks = 100, 
     main = expression("Histogram of "* hat(p)[MLE]), 
     xlab = expression(hat(p)[MLE]),
     freq=F
)
curve(dnorm(x, mean=true_p,
            sd= sqrt( ( (true_p ** 2) * (1 - true_p) ) / (n_obs * true_size))),
add=T, col="red", lwd=2)

legend("topright", legend = expression("Asymptotic Normal "* hat(p)[MLE]), 
       col="red", lwd=2, lty = 1, cex = 0.6)
```
