---
title: "Confidence and Credible Intervals"
---

## Confidence Interval

To remember, in Homework 1, we solved that for $X_1,...,X_n \sim \text{NegBin}(r, p)$ $\hat{p}_{MLE} = \frac{r}{r + \bar{x}}$.

In Homework #3, we established both that

$$
  \sqrt{n} (\hat{p}_{MLE} - p) \sim N\left(0, \frac{p^2(1-p)}{r}\right)
$$

and

$$
\hat{p}_{MLE} \overset{\cdot}{\sim} N\left(p, \frac{p^2(1-p)}{nr} \right)
$$This means that as the number of data points approaches infinity, $\hat{p}_{MLE}$ is approximately Normal, with a mean of $p$ and a variance of $\frac{p^2(1-p)}{nr}$.

Therefore, an approximate 95% confidence interval for $p$ is : $\hat{p}_{MLE} \pm 2 \sqrt{\frac{p^2(1-p)}{nr}}$. However, we do not know the true value of $p$, so we have two options in how we can proceed.

### Plug-In

We can try plugging in $\hat{p}_{MLE}$ for $p$ in this equation. This means that the approximate 95% confidence interval is:

$$
\begin{aligned}
\hat{p} \pm 2 \sqrt{\frac{\hat{p}_{MLE}^2(1-\hat{p}_{MLE})}{nr}} 
&= \hat{p} \pm 2 \sqrt{\frac{\left( \frac{r}{r + \bar{x}} \right)^2 \left( 1-\frac{r}{r + \bar{x}} \right)}{nr}} \\
&= \hat{p} \pm 2 \sqrt{\frac{\left( \frac{r}{r + \bar{x}} \right)^2 \left( \frac{r + \bar{x}}{r + \bar{x}}-\frac{r}{r + \bar{x}} \right)}{nr}} \\
&= \hat{p} \pm 2 \sqrt{\frac{\left( \frac{r}{r + \bar{x}} \right)^2 \left( \frac{\bar{x}}{r + \bar{x}} \right)}{nr}} \\
&= \hat{p} \pm 2 \sqrt{\frac{r^2\bar{x}}{nr(r + \bar{x})^3}} \\
&= \hat{p} \pm 2 \sqrt{\frac{r\bar{x}}{n(r + \bar{x})^3}}
\end{aligned}
$$

Going back to my hospital dataset:

```{web-r}
dat <- read.csv('/Users/ryderfried/Documents/2025-2026/Spring/STATS200Q/transmission_pairs_covid_v2.csv')
x <- as.vector(table(dat$infector_id)) - 1
x_bar = mean(x)
n = length(x)
print(c(x_bar, n))
```

I had $\bar{x} \approx 0.7435, n=807$. Let's say $r = 0.5$.

I then have:

$$
\begin{aligned}
\hat{p} \pm 2 \sqrt{\frac{r\bar{x}}{n(r + \bar{x})^3}} \\
\frac{r}{r+\bar{x}} \pm 2 \sqrt{\frac{r\bar{x}}{n(r + \bar{x})^3}} \\
\frac{0.5}{0.5+0.7435} \pm 2 \sqrt{\frac{(0.5)(0.7435)}{807(0.5 + 0.7435)^3}} \\
0.4021 \pm 2 \sqrt{0.00023958}
\end{aligned}
$$

So, the approximate plug-in 95% confidence interval for $p$ is $[0.3711, 0.4331]$.

### Direct Computation

Instead of plugging in $\hat{p}_{MLE}$ for $p$, we can try to solve for what values of $p$ make up the confidence interval.

We established earlier that:

$\sqrt{n} (\hat{p}_{MLE} - p) \sim N\left(0, \frac{p^2(1-p)}{r}\right)$

This means that: $\hat{p}_{MLE} - p \sim N\left(0, \frac{p^2(1-p)}{nr}\right)$.

Furthermore, we can say that:

$\frac{\hat{p}_{MLE} - p}{\sqrt{ \frac{p^2(1-p)}{nr}}} \sim N(0, 1)$

As this has a standard deviation of 1, we can set up a 95% confidence interval to be:

$-2 \leq \frac{\hat{p}_{MLE} - p}{\sqrt{ \frac{p^2(1-p)}{nr}}} \leq 2$

$$
\begin{aligned}
\Bigg( \frac{\hat{p}_{MLE} - p}{\sqrt{ \frac{p^2(1-p)}{nr}}} \Bigg)^2 &\leq 4 \\
\frac{(\hat{p}_{MLE} - p)^2}{ \frac{p^2(1-p)}{nr}} &\leq 4 \\
\frac{nr(\hat{p}_{MLE} - p)^2}{p^2(1-p)} &\leq 4 \\
\hat{p}_{MLE}^2 -2\hat{p}_{MLE}p + p^2 &\leq \frac{4}{nr}p^2(1-p) \\
\hat{p}_{MLE}^2 -2\hat{p}_{MLE}p + p^2- \frac{4p^2}{nr} + \frac{4p^3}{nr} &\leq 0 \\
\frac{4}{nr}p^3 + (1- \frac{4}{nr})p^2 - 2\hat{p}_{MLE}p + \hat{p}_{MLE}^2&\leq 0 
\end{aligned}
$$

This is unfortunately not cleanly solvable for $p$, but we can graph it. If we say that $f(p) = \frac{4}{nr}p^3 + (1- \frac{4}{nr})p^2 - 2\hat{p}_{MLE}p + \hat{p}_{MLE}^2$, we can look at the zeros to see the values of $p$ at the edge of the confidence intervals.

For this sample, let's go back to the dataset I started with, where $\bar{x} = 0.7435, n=807$. Let's fix $r = 0.5$.

```{web-r}
r <- 0.5      

p_hat <- r / (r + x_bar)

# f(p)
cubic_f <- function(p) {
  a <- 4 / (n * r)
  (a * p^3) + (1 - a) * p^2 - (2 * p_hat) * p + p_hat^2
}

# ind roots of f(p) in two windown [0, p_hat] and [p_hat, 1]
lower_bound <- uniroot(cubic_f, interval = c(0, p_hat))$root
upper_bound <- uniroot(cubic_f, interval = c(p_hat, 1))$root


cat("95% Confidence Interval: [", round(lower_bound, 4), ",", round(upper_bound, 4), "]\n")
```

From the computation in the code above, we are approximately 95% confident that $p$ is in $[0.3727, 0.4346]$

## Credible Interval

In Homework 1, I solved that given a Beta$(\alpha, \beta)$ prior, the posterior distribution for $p$ is:

$f(p | x_1,..,x_n) \sim \text{Beta}(\alpha + nr, \beta + \sum_{i=1}^n x_i)$.

In Homework 1, I used a uniform prior, meaning $\alpha =1, \beta=1$. This means the posterior distribution given a uniform prior is:

$f(p | x_1,..,x_n) \sim \text{Beta}(1 + nr, 1 + \sum_{i=1}^n x_i)$.

For our 95% credible interval, we want the interval to cover 95% of the distribution with symmetric tails.

So, we need a left bound (LB) and right bound (RB), such that:

$\int_{0}^{LB} \frac{p^{(1+nr)-1} (1-p)^{(1+\sum x_i)-1}}{B(1+nr, 1+\sum x_i)} dp = 0.025$

$\int_{RB}^{1} \frac{p^{(1+nr)-1} (1-p)^{(1+\sum x_i)-1}}{B(1+nr, 1+\sum x_i)} dp = 0.025$

Unfortunately, we can't solve for LB and RB by hand. However, the computer can solve it for us, using the 'qbeta' function.

Again, we will use the same values from my hospital dataset, as before.

```{web-r}
r <- 0.5
sum_xi <- x_bar * n 
credible_range <- 0.95

# Posterior Parameters based on f(p | x) ~ Beta(1 + nr, 1 + sum x_i)
alpha_post <- 1 + (n * r)
beta_post  <- 1 + sum_xi

# Calculate Tail Areas
alpha_level <- 1 - credible_range
tail_area   <- alpha_level / 2

# 4. Solve for Credible Interval Bounds
LB <- qbeta(tail_area, 
            shape1 = alpha_post, 
            shape2 = beta_post, 
            lower.tail = TRUE)

RB <- qbeta(tail_area, 
            shape1 = alpha_post, 
            shape2 = beta_post, 
            lower.tail = FALSE)

credible_interval <- c(LB, RB)
names(credible_interval) <- c("Left Bound", "Right Bound")

print(credible_interval)
```

From the computation in the code above, conditional on my uniform prior, the credible interval states that there is a 95% chance $p$ is in $[0.3722, 0.4328]$.
