---
title: "Hypothesis Testing"
---

## Background

We have previously covered solving for $\hat{p}_{MLE}$ and $\hat{p}_{PM}$, evaluating them, and setting up confidence and credible intervals. Now, we will talk about a new topic: hypothesis testing.

This chapter is the first of three about hypothesis testing. The idea is that we have a default hypothesis about a parameter $\theta$. Let's say, for example, our null hypothesis is that $\theta_0 = 10$. Maybe this represents the number of symptoms per day of medical patients.

Now, let's say we are trying out a new drug and want to see if it is effective. So, maybe our alternative hypothesis is that $\theta_A = 5$, thus lowering the number of symptoms per day. Hypothesis testing is seeing whether, based on the data, we can reject the null hypothesis and accept the alternative.

Unlike when we solved for $\hat{p}_{MLE}$ and $\hat{p}_{PM}$, the result of a hypothesis test is strictly binary. It is only where we accept/reject the null hypothesis.

Frequentist hypothesis testing is all about the Neyman-Pearson lemma. This says that if we have a distribution $f_\theta(x)$, and $H_0: \theta = \theta_0$ and $H_A: \theta = \theta_A$, then we want to reject $H_0$ when $\frac{f_{\theta_A}(x)}{f_{\theta_0}(x)}$ is maximized. This is in order to maximize the power of our hypothesis test.

To understand why this works, let's look at hypothesis testing as a constrained optimization problem. Theoretically we would want our test to never make a mistake. This means we would want it to only accept the null when $H_0$ is true and only reject when $H_0$ is false. In reality, there is a strict trade-off between committing a Type I error (rejecting $H_0$ despite $H_0$ being true) and maximizing power (correctly rejecting $H_0$). We handle this by setting a hard cap on our Type I error (which is referred to as $\alpha$), typically at $\alpha = 0.05$. Type I error can be very harmful, for example leading us to deem a drug as effective even if it isn't. This is why we cap it at $0.05$.

Once this budget is locked in, the Neyman-Pearson lemma tells us exactly we can maximize our power (correctly rejecting $H_0$) while staying within our $\alpha$ allocation. You can think of the likelihood ratio $\frac{f_{\theta_A}(x)}{f_{\theta_0}(x)}$ as a benefit-to-cost efficiency metric for every possible data outcome. The numerator represents the "benefit" (gaining power if $H_A$ is true), while the denominator represents the "cost" (eating away at our fixed $\alpha$ budget if $H_0$ is true). By sorting our outcomes and choosing to reject $H_0$ only when this ratio is at its highest, the lemma mathematically guarantees that we have constructed the most powerful test possible for our chosen significance level.

In class, we showed that this principle extends into one-sided hypothesis testing. Imagine instead of saying, $H_A: \theta = 5$, we said $H_A: \theta < 10$. To solve for this, we want to find a ratio that maximizes the power for every possible $\theta$ below 10. What we showed in class is that we can just choose any number below 10 (let's say 2 for this example), and the values the maximize $\frac{f_{\theta_A = 2}(x)}{f_{\theta_0}(x)}$ are the same values that maximize $\frac{f_{\theta_A = 7}(x)}{f_{\theta_0}(x)}$ or $\frac{f_{\theta_A = 9}(x)}{f_{\theta_0}(x)}$, or any value below 10. So, we can just choose one one these values below 10 to set up the ratio for $H_A: \theta < 10$. 

Because this single ratio maximizes the power across the entire range of possible one-sided alternative values simultaneously, the resulting test is called a Uniformly Most Powerful (UMP) test.

## Uniformly Most Powerful Test

Let's apply this to my dataset. First, let's bring my hospital dataset into R.

```{webr-r}
dat <- read.csv("https://raw.githubusercontent.com/Ryder4real/STATS200Q_Book/main/transmission_pairs_covid_v2.csv")
x <- as.vector(table(dat$infector_id)) - 1
```

In my dataset, remember that the data that has a negative binomial distribution is the number of people each person infected beyond the first person (This is because all infectors in the dataset infected at least one person, so we subtract one to have a healthy amount of zero values). Google says that for the Flu, the average person with the disease spreads it to 1-2 people. As our negative binomial distribution only counts the number of additional people each person infects after the first, then setting $E[X] = 0.5$ feels fair. In other words, for the flu, it reasonable to say the average person in a hospital with a disease infects 0.5 extra people. That would means that $\mathbb{E}[X] = \frac{r(1-p)}{p} = 0.5$.

Isolating for $p$, we get:

$$
\begin{aligned}
\mathbb{E}[X] &= \frac{r(1-p)}{p} \\
\frac{p}{1-p} &= \frac{r}{\mathbb{E}[X]} \\
\frac{1-p}{p} &= \frac{\mathbb{E}[X]}{r} \\
\frac{1}{p} - 1 &= \frac{\mathbb{E}[X]}{r} \\
\frac{1}{p} &= \frac{\mathbb{E}[X] + r}{r} \\
p &= \frac{r}{\mathbb{E}[X] + r}
\end{aligned}
$$

So, we set $\mathbb{E}[x]$ to be 0.5. Let's say for the sake of this example that we set $r$ to be $0.75$. In this scenario, we get $p = \frac{0.75}{0.5+0.75} = 0.6$.

So, our null hypothesis is $H_0$: $p = 0.6$. Now, we are curious if maybe COVID is more infectious than the flu (not considering other considerations like how my dataset is limited to people only already at the hospital). This would mean that $E[X]$ is greater than 0.5, and as $\mathbb{E}[X] = \frac{r(1-p)}{p}$, a smaller $p$ leads to a larger $E[X]$.

This means that:

$H_0$: $p = 0.6$

$H_A$: $p < 0.6$

As mentioned in the Background section, to figure out the best X values to reject when $p<0.6$, all we need to do is choose one $p<0.6$, and the same will hold true for rest. Let's proceed with $p=0.3$.

Again, let's proceed with $r=0.75$.

NegBin$(r, p)$ follows the distribution $\binom{x + r - 1}{x} p^r (1 - p)^x$:

So, our $H_0$ gives us NegBin$(r, p=0.6)$, which follows the distribution: $f_0(x) = \prod _{i=1}^n \binom{x_i + r - 1}{x_i} 0.6^r (1 - 0.6)^{x_i}$.

Our $H_A$ gives us NegBin$(r, p=0.3)$, which follows the distribution: $f_A(x) = \prod _{i=1}^n \binom{x_i + r - 1}{x_i} 0.3^r (1 - 0.3)^{x_i}$.

We want to to maximize $\frac{f_A(x)}{f_0(x)} = \frac{\prod _{i=1}^n \binom{x_i + r - 1}{x_i} 0.3^r (1 - 0.3)^{x_i}}{\prod _{i=1}^n \binom{x_i + r - 1}{x_i} 0.6^r (1 - 0.6)^{x_i}}$, as these are the $X$ values that we maximize our $\frac{\text{Power}}{\alpha}$. In other words, when this value ratio is maximized, we have the best ratio for decreasing the odds of a Type II Error while still protecting against Type I Errors.

So, let's maximize:

$$
\begin{aligned}
\frac{f_A(x)}{f_0(x)} &= \frac{\prod _{i=1}^n \binom{x_i + r - 1}{x_i} 0.3^r (1 - 0.3)^{x_i}}{ \prod_{i=1}^n \binom{x_i + r - 1}{x_i} 0.6^r (1 - 0.6)^{x_i}} \\
\frac{f_A(x)}{f_0(x)} &= \frac{ \Big( \prod _{i=1}^n \binom{x_i + r - 1}{x_i} \Big) 0.3^{nr} (1 - 0.3)^{\sum x_i}}{ \Big( \prod _{i=1}^n \binom{x_i + r - 1}{x_i} \Big) 0.6^{nr} (1 - 0.6)^{\sum x_i}} \\
&= \frac{0.3^{nr} (1 - 0.3)^{\sum_{i=1}^n x_i}}{ 0.6^{nr} (1 - 0.6)^{\sum_{i=1}^n x_i}} \\
&\propto \frac{0.7^{\sum_{i=1}^n x_i}}{0.4^{\sum_{i=1}^n x_i}} \\
&\propto \Big(\frac{0.7}{0.4}\Big)^ {\sum_{i=1}^n x_i} \\
\end{aligned}
$$

To maximize, $\Big(\frac{0.7}{0.4}\Big)^{\sum_{i=1}^n x_i}$, we want to reject when $\sum_{i=1}^n x_i$ is as large as possible.

So, this means we set up: $P(\sum_{i=1}^n x_i \geq c) = 0.05$.

The sum of many NegBin$(p, r)$ random variables is NegBin$(n \cdot r, p)$, My COVID hospital dataset had 807 patients, so $n = 807$.

```{webr-r}
n = length(x)
n
```

So, we would use the `qnbinom` R function to set up a sum from $c$ to $\infty$ over the $H_0$ PMF that covers the upper $5\%$ (at most) of the distribution.

```{webr-r}
r = 0.75
alpha = 0.05
p = 0.6
reject_val = qnbinom(1 - alpha, r * n, p)
reject_val
```

We then check to see how much of the mass is in this value or above (I write `reject_val - 1` because we want the mass above whichever value is inputted into the `pnbinom` function):

```{webr-r}
1 - pnbinom(reject_val - 1, n * r, p)
```

We are above 0.05. So, we need to move our rejection bound up one value, to take up less of the mass.

```{webr-r}
new_reject_val = reject_val + 1
1 - pnbinom(new_reject_val - 1, n * r, p)
```

$\alpha$ is now below $0.05$!

```{webr-r}
new_reject_val
```

So, $c = 448$

So, we reject if $H_0$ when $\sum x_i \ge 448$.

Now, let's see if reject $H_0$ in my dataset.

```{webr-r}
observed_sum <- sum(x)
observed_sum
```

As $600 > c$ (which was $448$ in my COVID hospital dataset), we reject $H_0$. This implies that we accept the alternative hypothesis that COVID is more contagious than the flu (though this dataset is not perfect as it only consists of people already in the hospital who infected at least 1 person, so I do not want to extrapolate too much).
