---
title: "Simulating Confidence Intervals"
---

## Background

In the prevous chapter, we talked about using confidence and credible intervals. For the frequentist calculation, we assumed large $n$ and used a Normal approximation for $\hat{p}_{MLE}$. For our credible interval, we chose a conjugate prior so we could solve for the posterior distribution. 

However, what if we didn't want to resort to using a Normal approximatation for our confidence interval? Additionally, what if we don't know the our posterior distribution for the credible interval?

Statisticians have had come up with computationally-intense mechanisms to work around these issues. For frequentists, this involves the  parametric and nonparametric bootstrap. In the former, you assume your population follows a certain distribution, then use the MLE from your sample to generate more datasets. In the latter, you re-sample more datasets from your original sample with replacement. For both, you then look at the MLEs of your many generated datasets.

The Bayesian Process involves a Metropolis-Hastings Markov Chain Monte Carlo. Let's say we want to come up with estimator for $\theta$ in Distribution B. To do this, we first pick a starting Distribution A (that has the same domain as Distribution B) and continuously sample from it. After each sample, we establish a probability based on the likelihood that the sample could have been generated by Distributions A & B. We then keep the sample with this probability. The idea, is after a burn-in period, despite being generated from Distribution A, the kept samples will actually resemble Distribution B. I know this can be confusing, and I will explain the intricacies in more detail later in the chapter.

## Bootstrapping

First, let's bring my hospital dataset into R.

```{webr-r}
dat <- read.csv("https://raw.githubusercontent.com/Ryder4real/STATS200Q_Book/main/transmission_pairs_covid_v2.csv")
x <- as.vector(table(dat$infector_id)) - 1
```

### Parametric Bootstrap

If we say $X \sim \text{NegBin}(r, p)$, and we have $r = 0.5$, then as I calculated in Chapter 1, $\hat{p}_{MLE} = \frac{r}{r + \bar{x}} = \frac{0.5}{0.5 + 0.7435} = 0.402$.

```{webr-r}
r = 0.5
n = length(x)
x_bar = sum(x) / n 
p_mle = r / (r + x_bar)
```

So, using a parametric bootstrap, we can simulate many new datasets from the Negabtive Binomial with my $\hat{p}_{MLE}$. Then, we can calculate the MLE of each of these datasets. A histogram of the MLE values of these datasets can be seen in the code block below.

```{webr-r}
p.pboot <- replicate(10000, {
    # Generate dataset
    x.pboot = rnbinom(n, r, p_mle)
    
    # Calculate new MLE
    x.pboot.bar = sum(x.pboot) / n
    p.pboot.mle = r / (r + x.pboot.bar)
    p.pboot.mle
  }
)

hist(p.pboot)
```

A $95\%$ confidence interval is generated in the code block below.

```{webr-r}
quantile(p.pboot, c(.025, .975))
```

So, our approximate 95% confidence interval for $p$ using Parametric Bootstrapping is about $[0.3738, 0.4336]$, depending on the simulation.

### Nonparametric Bootstrap

for the nonparametric boostrap, we just re-sample new datasets from our sample with replacement, and take the MLE sfrom each of these simulated datasets. A histogram of the MLE values of these datasets can be seen in the code block below.

```{webr-r}
p.npboot <- replicate(10000, {
  
    # Generate new sample (with replacement) from our above sample
    x.npboot <- sample(x, size=n, replace=TRUE)
    
    # Calculate new MLE
    x.npboot.bar = sum(x.npboot) / n
    p.npboot.mle = r / (r + x.npboot.bar)
    p.npboot.mle
  }
)

hist(p.npboot)
```

A $95\%$ confidence interval is generated in the code block below.

```{webr-r}
quantile(p.npboot, c(.025, .975))
```

So, our approximate 95% confidence interval for $p$ using Nonparametric Bootstrapping is about $[0.3714, 0.4360]$, depending on the simulation.

### Comparing Confidence Intervals

Combining last week and this week, I have now computed four different 95% confidence intervals for $p$.

They are listed below:

1.  Using CLT with $\hat{p}_{MLE}$ plug in for $p$ in $I(p)$: $[0.3711, 0.4331]$
2.  Using CLT with direct computation for $p$ in $I(p)$: $[0.3727, 0.4346]$
3.  Parametric Bootstrap: $[0.3738, 0.4336]$ (with volatility depending on simulation)
4.  Nonparametric Bootstrap: $[0.3714, 0.4360]$ (with volatility depending on simulation)

Computing for the **range** of the 95% confidence interval, we have:

Using CLT with $\hat{p}_{MLE}$ plug in for $p$ in $I(p)$: $0.0620$

Using CLT with direct computation for $p$ in $I(p)$: $0.0619$

Parametric Bootstrap: $0.0598$

Nonparametric Bootstrap: $0.0646$

So, using the first simulations I ran, the parametric bootstrap's 95% confidence interval had the smallest range, while the nonparametric bootstrap had the largest range. I am not sure if this means anything, as this may have been strictly due to a weird simulation.

## Metropolis Hastings

In Chapter 1, I calculated a Bayesian posterior mean for my data using a Beta prior. I solved that:

$f(p | x) \propto p^{\alpha + nr - 1} (1-p)^{\beta + \sum x_i - 1}$.

For my Beta$(1,1)$ (Uniform) prior, this means that:

$f(p | x) \propto p^{1 + nr - 1} (1-p)^{1 + \sum x_i - 1}$

$f(p | x) \propto p^{nr} (1-p)^{\sum x_i}$.

Now, instead of recognizing the beta distribution, let's instead run the Metropolis Hastings Algorithm.

The algorithm will work like this. Imagine we start with a list of length one that contains one random sample from my prior distribution (uniform in my case). I will then generate another sample from my prior distribution and compare it to the last element in my list (which in this case would just be the first generated sample). 

With a certain likelihood (that I will explain in a second), I will add this new generated sample to my list. With probability $[1 - \text{that_likelihood}]$, I will forget about this new sample and just add that last value in my list, to my list again. I will then generate more and more samples and continue this process over and over.

To write out the probability from earlier, imagine $f$ is the prior distribution, $g$ is the distribution we are interested in, and we are comparing new sample $x_j$ and previous sample $x_{j-1}$. The likelihood of adding generated sample $x_j$ to the list is $\frac{g(x_j)}{g(x_{j-1})} \cdot \frac{f(x_{j-1})}{f(x_j)}$. The likelihood of adding $x_{j-1}$ again is $1 - \Big( \frac{g(x_j)}{g(x_{j-1})} \cdot \frac{f(x_{j-1})}{f(x_j)} \Big)$

However, as I am using a $\text{Uniform}(0,1)$ prior, $f(x) = 1$ for every $x$. This means that the we keep the generated sample with likelihood $\frac{g(x_j)}{g(x_{j-1})}$, and forget the generated sample and add the older sample to our list again with likelihood $\Big(1 - \frac{g(x_j)}{g(x_{j-1})} \Big)$.

After generating enough samples, and then removing the first chunk of values from my list (called a burn-in period), the remainder of my list should resemble $g$, the posterior distribution, which is the Negative Binomial in my case.

To avoid numerical underflow, we will compute $e^{log(f(p | x))}$.

$f(p | x) \propto e^{ nr \log (p) + {\sum x_i} \log (1-p) + C}$.

I will generate $15000$ samples and have a burn-in period of $5000$.

```{webr-r}

# This function calculates the posterior probability (without accounting for the constant term).
# To avoid numerical underflow, we will first calculate the log, and then do e ^ (log(prob))

post <- function(p) {
  # calculate log posterior (for numerical stability)
  log.p.post <- log(p) * (n * r) +  sum(x) * log(1-p)
  exp(log.p.post)
}

# Start with an arbitrary value of p.
p.post <- c(0.5)

# Run Metropolis-Hastings for 15000 steps
for(i in 1:15000) {

  p.curr <- p.post[length(p.post)]
  
  # Propose a new value of p. Let's choose from uniform(0,1). Let's call this q.
  p.prop <- runif(1)
  
  # calculate probability of choosing new_p.
  # This is (post(new) * q(old)) / (post(old) ( q(new)))
  prob <- min(1,
    (post(p.prop) * dunif(p.curr, 0, 1) /
      (post(p.curr) * dunif(p.prop, 0, 1)))
  )

  # add new p value to list
  p.new <- sample(c(p.prop, p.curr),
                      size=1, prob=c(prob, 1-prob))
  p.post <- c(p.post, p.new)
}

# Keep the latter 10,000 samples
late.p.post <- p.post[5001:15000]

# We can estimate the posterior mean by taking the mean of these samples.
mean(late.p.post)
```

Here, from running the code above, my Metropolis-Hastings posterior mean is around $0.401$, depending on the simulation.

In Chapter 1, instead of using a simulation, I recognized that my posterior followed a  $\text{Beta}(1 + nr, 1+ \sum_{i=1}^n x_i)$ distribution. In that situation, my posterior mean was $0.401$.

Now, let's look at the distribution of my Metropolis-Hastings $\hat{p}$ in the code block below.

```{webr-r}
hist(late.p.post)
```

Also, let's generate a credible interval from my Metropolis-Hastings data from the code block below.

```{webr-r}
quantile(late.p.post, c(.025, .975))
```

Here, my Metropolis-Hastings approximate 95% credible interval is around $[0.3701, 0.4283]$, depending on the simulation.

When I did this from the Beta function in Chapter 4 using the `qbeta` function, my 95% credible interval was $[0.3722, 0.4328]$.

So let's further compare about these 95% credible intervals:

**Range**:

Direct computation of the posterior distribution: $0.0606$

Metropolis-Hastings: $0.0582$

So, my approximate M-H 95% credible interval had a slightly smaller spread, though again, this may have just been because of a weird simulation.
